[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "deepslyme"
version = "0.0.2rc3"
description = "Placeholder for slyme series."
readme = "README.md"
authors = [{ name = "The SlymeLab Team" }]
license = "Apache-2.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.9"
dependencies = []

[project.urls]
Homepage = "https://github.com/slymelab/deepslyme"

[tool.hatch.build.targets.wheel]
packages = ["src/deepslyme"]
